part of 'theme.dart';

/// Generated by Forui CLI.
///
/// Color tokens and theme extensions for the generated theme.
final FColors lightColors = FColors(
  brightness: .light,
  systemOverlayStyle: SystemUiOverlayStyle(
    statusBarColor: Colors.transparent,
    statusBarIconBrightness: Brightness.dark,
    statusBarBrightness: Brightness.light,
    systemNavigationBarColor: Colors.transparent,
    systemNavigationBarDividerColor: Colors.transparent,
    systemNavigationBarIconBrightness: Brightness.dark,
    systemNavigationBarContrastEnforced: false,
  ),
  barrier: Color(0x33000000),
  background: Color(0xFFFFFFFF),
  foreground: Color(0xFF0C0A09),
  primary: Color(0xFFC10007),
  primaryForeground: Color(0xFFFEF2F2),
  secondary: Color(0xFFF3F1F1),
  secondaryForeground: Color(0xFF1D1816),
  muted: Color(0xFFF3F1F1),
  mutedForeground: Color(0xFF7C6D67),
  destructive: Color(0xFFE7000B),
  destructiveForeground: Color(0xFFFAFAFA),
  error: Color(0xFFE7000B),
  errorForeground: Color(0xFFFAFAFA),
  card: Color(0xFFFFFFFF),
  border: Color(0xFFE8E4E3),
  extensions: const [AppColors()],
);

final FColors darkColors = FColors(
  brightness: .dark,
  systemOverlayStyle: SystemUiOverlayStyle(
    statusBarColor: Colors.transparent,
    statusBarIconBrightness: Brightness.light,
    statusBarBrightness: Brightness.dark,
    systemNavigationBarColor: Colors.transparent,
    systemNavigationBarDividerColor: Colors.transparent,
    systemNavigationBarIconBrightness: Brightness.light,
    systemNavigationBarContrastEnforced: false,
  ),
  barrier: Color(0x7A000000),
  background: Color(0xFF0C0A09),
  foreground: Color(0xFFFBFAF9),
  primary: Color(0xFF9F0712),
  primaryForeground: Color(0xFFFEF2F2),
  secondary: Color(0xFF2B2422),
  secondaryForeground: Color(0xFFFBFAF9),
  muted: Color(0xFF2B2422),
  mutedForeground: Color(0xFFABA09C),
  destructive: Color(0xFFFF6467),
  destructiveForeground: Color(0xFFFAFAFA),
  error: Color(0xFFFF6467),
  errorForeground: Color(0xFFFAFAFA),
  card: Color(0xFF1D1816),
  border: Color(0x1AFFFFFF),
  extensions: const [AppColors()],
);

FColors appColors({
  required AppBaseColor base,
  required AppPrimaryColor primary,
  required bool dark,
}) {
  if (base == AppBaseColor.defaultColor) base = AppBaseColor.taupe;
  if (primary == AppPrimaryColor.defaultColor) primary = AppPrimaryColor.red;
  final colors = (dark ? darkColors : lightColors).copyWith(
    background: Color(_baseTokens(base, dark).$1),
    foreground: Color(_baseTokens(base, dark).$2),
    primary: Color(_baseTokens(base, dark).$3),
    primaryForeground: Color(_baseTokens(base, dark).$4),
    secondary: Color(_baseTokens(base, dark).$5),
    secondaryForeground: Color(_baseTokens(base, dark).$6),
    muted: Color(_baseTokens(base, dark).$5),
    mutedForeground: Color(_baseTokens(base, dark).$7),
    card: Color(_baseTokens(base, dark).$8),
    border: Color(dark ? 0x1AFFFFFF : _baseTokens(base, dark).$9),
  );
  final pair = _primaryTokens(primary, dark);
  return pair == null
      ? colors
      : colors.copyWith(
          primary: Color(pair.$1),
          primaryForeground: Color(pair.$2),
        );
}

(int, int, int, int, int, int, int, int, int) _baseTokens(
  AppBaseColor base,
  bool dark,
) => switch ((base, dark)) {
  (AppBaseColor.defaultColor, _) => throw StateError(
    'Default base is resolved',
  ),
  (AppBaseColor.neutral, false) => (
    0xFFFFFFFF,
    0xFF0A0A0A,
    0xFF171717,
    0xFFFAFAFA,
    0xFFF5F5F5,
    0xFF171717,
    0xFF737373,
    0xFFFFFFFF,
    0xFFE5E5E5,
  ),
  (AppBaseColor.neutral, true) => (
    0xFF0A0A0A,
    0xFFFAFAFA,
    0xFFE5E5E5,
    0xFF171717,
    0xFF262626,
    0xFFFAFAFA,
    0xFFA1A1A1,
    0xFF171717,
    0,
  ),
  (AppBaseColor.stone, false) => (
    0xFFFFFFFF,
    0xFF0C0A09,
    0xFF1C1917,
    0xFFFAFAF9,
    0xFFF5F5F4,
    0xFF1C1917,
    0xFF79716B,
    0xFFFFFFFF,
    0xFFE7E5E4,
  ),
  (AppBaseColor.stone, true) => (
    0xFF0C0A09,
    0xFFFAFAF9,
    0xFFE7E5E4,
    0xFF1C1917,
    0xFF292524,
    0xFFFAFAF9,
    0xFFA6A09B,
    0xFF1C1917,
    0,
  ),
  (AppBaseColor.zinc, false) => (
    0xFFFFFFFF,
    0xFF09090B,
    0xFF18181B,
    0xFFFAFAFA,
    0xFFF4F4F5,
    0xFF18181B,
    0xFF71717B,
    0xFFFFFFFF,
    0xFFE4E4E7,
  ),
  (AppBaseColor.zinc, true) => (
    0xFF09090B,
    0xFFFAFAFA,
    0xFFE4E4E7,
    0xFF18181B,
    0xFF27272A,
    0xFFFAFAFA,
    0xFF9F9FA9,
    0xFF18181B,
    0,
  ),
  (AppBaseColor.mauve, false) => (
    0xFFFFFFFF,
    0xFF0C090C,
    0xFF1D161E,
    0xFFFAFAFA,
    0xFFF3F1F3,
    0xFF1D161E,
    0xFF79697B,
    0xFFFFFFFF,
    0xFFE7E4E7,
  ),
  (AppBaseColor.mauve, true) => (
    0xFF0C090C,
    0xFFFAFAFA,
    0xFFE7E4E7,
    0xFF1D161E,
    0xFF2A212C,
    0xFFFAFAFA,
    0xFFA89EA9,
    0xFF1D161E,
    0,
  ),
  (AppBaseColor.olive, false) => (
    0xFFFFFFFF,
    0xFF0C0C09,
    0xFF1D1D16,
    0xFFFBFBF9,
    0xFFF4F4F0,
    0xFF1D1D16,
    0xFF7C7C67,
    0xFFFFFFFF,
    0xFFE8E8E3,
  ),
  (AppBaseColor.olive, true) => (
    0xFF0C0C09,
    0xFFFBFBF9,
    0xFFE8E8E3,
    0xFF1D1D16,
    0xFF2B2B22,
    0xFFFBFBF9,
    0xFFABAB9C,
    0xFF1D1D16,
    0,
  ),
  (AppBaseColor.mist, false) => (
    0xFFFFFFFF,
    0xFF090B0C,
    0xFF161B1D,
    0xFFF9FBFB,
    0xFFF1F3F3,
    0xFF161B1D,
    0xFF67787C,
    0xFFFFFFFF,
    0xFFE3E7E8,
  ),
  (AppBaseColor.mist, true) => (
    0xFF090B0C,
    0xFFF9FBFB,
    0xFFE3E7E8,
    0xFF161B1D,
    0xFF22292B,
    0xFFF9FBFB,
    0xFF9CA8AB,
    0xFF161B1D,
    0,
  ),
  (AppBaseColor.taupe, false) => (
    0xFFFFFFFF,
    0xFF0C0A09,
    0xFF1D1816,
    0xFFFBFAF9,
    0xFFF3F1F1,
    0xFF1D1816,
    0xFF7C6D67,
    0xFFFFFFFF,
    0xFFE8E4E3,
  ),
  (AppBaseColor.taupe, true) => (
    0xFF0C0A09,
    0xFFFBFAF9,
    0xFFE8E4E3,
    0xFF1D1816,
    0xFF2B2422,
    0xFFFBFAF9,
    0xFFABA09C,
    0xFF1D1816,
    0,
  ),
};

(int, int)? _primaryTokens(AppPrimaryColor color, bool dark) => switch (color) {
  AppPrimaryColor.defaultColor => throw StateError(
    'Default primary is resolved',
  ),
  AppPrimaryColor.base => null,
  AppPrimaryColor.amber => (dark ? 0xFF973C00 : 0xFFBB4D00, 0xFFFFFBEB),
  AppPrimaryColor.blue => (dark ? 0xFF193CB8 : 0xFF1447E6, 0xFFEFF6FF),
  AppPrimaryColor.cyan => (dark ? 0xFF005F78 : 0xFF007595, 0xFFECFEFF),
  AppPrimaryColor.emerald => (dark ? 0xFF006045 : 0xFF007A55, 0xFFECFDF5),
  AppPrimaryColor.fuchsia => (dark ? 0xFF8A0194 : 0xFFA800B7, 0xFFFDF4FF),
  AppPrimaryColor.green => (dark ? 0xFF016630 : 0xFF008236, 0xFFF0FDF4),
  AppPrimaryColor.indigo => (dark ? 0xFF372AAC : 0xFF432DD7, 0xFFEEF2FF),
  AppPrimaryColor.lime => (dark ? 0xFF7CCF00 : 0xFF9AE600, 0xFF35530E),
  AppPrimaryColor.orange => (dark ? 0xFF9F2D00 : 0xFFCA3500, 0xFFFFF7ED),
  AppPrimaryColor.pink => (dark ? 0xFFA3004C : 0xFFC6005C, 0xFFFDF2F8),
  AppPrimaryColor.purple => (dark ? 0xFF6E11B0 : 0xFF8200DB, 0xFFFAF5FF),
  AppPrimaryColor.red => (dark ? 0xFF9F0712 : 0xFFC10007, 0xFFFEF2F2),
  AppPrimaryColor.rose => (dark ? 0xFFA50036 : 0xFFC70036, 0xFFFFF1F2),
  AppPrimaryColor.sky => (dark ? 0xFF00598A : 0xFF0069A8, 0xFFF0F9FF),
  AppPrimaryColor.teal => (dark ? 0xFF005F5A : 0xFF00786F, 0xFFF0FDFA),
  AppPrimaryColor.violet => (dark ? 0xFF5D0EC0 : 0xFF7008E7, 0xFFF5F3FF),
  AppPrimaryColor.yellow => (dark ? 0xFFF0B100 : 0xFFFDC700, 0xFF733E0A),
};

/// Provides convenient access to theme extensions on [FColors].
///
/// ```dart
/// final accent = context.theme.colors.app.accent; ✅
///
/// // Alternatively, you can create a getter to access extension fields directly.
/// final accent = context.theme.colors.accent; ✅
///
/// final accent = context.theme.colors.extension<AppColors>().accent; ❌
/// ```
extension FColorsExtensions on FColors {
  AppColors get app => extension<AppColors>();
}

/// Custom color tokens unique to your app.
///
/// Add your fields below, then implement [copyWith], [lerp], [==], and [hashCode].
/// See https://api.flutter.dev/flutter/material/ThemeExtension-class.html.
class AppColors extends ThemeExtension<AppColors> {
  // TODO: add your color fields here:
  // final Color accent;

  const AppColors();

  @override
  AppColors copyWith() => const AppColors();

  @override
  AppColors lerp(covariant AppColors? other, double t) {
    if (other == null) {
      return this;
    }
    return const AppColors();
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppColors && runtimeType == other.runtimeType;

  @override
  int get hashCode => runtimeType.hashCode;
}
