part of 'theme.dart';

/// Generated by Forui CLI.
///
/// Icon tokens for the generated theme.
FIcons _icons() => FIcons(
  arrowLeft: const _Icon(TablerIcons.arrowLeft, scale: 1.1),
  calendar: const _Icon(TablerIcons.calendar, scale: 1.1),
  check: const _Icon(TablerIcons.check, scale: 1.1),
  chevronDown: const _Icon(TablerIcons.chevronDown),
  chevronLeft: const _Icon(TablerIcons.chevronLeft),
  chevronRight: const _Icon(TablerIcons.chevronRight),
  chevronUp: const _Icon(TablerIcons.chevronUp),
  chevronsUpDown: const _Icon(TablerIcons.selector, scale: 1.1),
  circleAlert: const _Icon(TablerIcons.alertCircle, scale: 1.1),
  clock4: const _Icon(TablerIcons.clockHour4, scale: 1.1),
  ellipsis: const _Icon(TablerIcons.dots),
  error: const _Icon(TablerIcons.alertCircle, scale: 1.1),
  eye: const _Icon(TablerIcons.eye, scale: 1.1),
  eyeClosed: const _Icon(TablerIcons.eyeOff),
  gripHorizontal: const _Icon(TablerIcons.gripHorizontal),
  gripVertical: const _Icon(TablerIcons.gripVertical),
  loader: const _Icon(TablerIcons.loader, scale: 1.1),
  loaderCircle: const _Icon(TablerIcons.loader2),
  loaderPinwheel: const _Icon(TablerIcons.windmill, scale: 1.1),
  search: const _Icon(TablerIcons.search),
  userRound: const _Icon(TablerIcons.userCircle),
  x: const _Icon(TablerIcons.x),
);

class _Icon implements FIcon {
  final IconData icon;
  final double scale;

  const _Icon(this.icon, {this.scale = 1});

  @override
  Widget call(BuildContext _, {String? semanticsLabel}) => Builder(
    builder: (context) => Transform.translate(
      offset: Offset(0, -0.05 * (IconTheme.of(context).size ?? 24)),
      child: Transform.scale(
        scale: scale,
        child: Icon(icon, semanticLabel: semanticsLabel),
      ),
    ),
  );

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is _Icon && icon == other.icon && scale == other.scale;

  @override
  int get hashCode => Object.hash(icon, scale);
}
