import 'package:forui/forui.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:tabler_icons_plus/tabler_icons_plus.dart';

import '../features/settings/app_settings.dart';

part 'colors.dart';
part 'typography.dart';
part 'style.dart';
part 'icons.dart';

/// Generated by Forui CLI.
///
/// Regenerate using "dart forui theme create --preset gmtwcc".
///
/// Modify the generated function bodies to create your own custom style.
/// Then, call the modified function and pass it to [FTheme].
///
/// You can also generate styles to be used in the generated [FThemeData] using:
/// ```shell
/// dart run forui style create [styles]
/// ```
///
/// See:
/// * https://forui.dev/docs/guides/customizing-themes for customizing themes.
/// * https://forui.dev/docs/guides/customizing-widget-styles for customizing individual widget styles.
FThemeData lightThemeFor({
  AppBaseColor base = AppBaseColor.defaultColor,
  AppPrimaryColor primary = AppPrimaryColor.defaultColor,
}) {
  // Change this to false to use the desktop variant of this theme.
  const touch = true;

  final colors = appColors(base: base, primary: primary, dark: false);

  final typography = _typography(colors: colors, touch: touch);

  final icons = _icons();

  final style = _style(colors: colors, typography: typography, touch: touch);

  return FThemeData(
    colors: colors,
    typography: typography,
    icons: icons,
    style: style,
    touch: touch,
  );
}

FThemeData darkThemeFor({
  AppBaseColor base = AppBaseColor.defaultColor,
  AppPrimaryColor primary = AppPrimaryColor.defaultColor,
}) {
  // Change this to false to use the desktop variant of this theme.
  const touch = true;

  final colors = appColors(base: base, primary: primary, dark: true);

  final typography = _typography(colors: colors, touch: touch);

  final icons = _icons();

  final style = _style(colors: colors, typography: typography, touch: touch);

  return FThemeData(
    colors: colors,
    typography: typography,
    icons: icons,
    style: style,
    touch: touch,
  );
}

FThemeData get lightTheme => lightThemeFor();
FThemeData get darkTheme => darkThemeFor();
